import { describe, expect, it } from 'vitest'
import { adifToQso, parseAdif, qsoToAdif, serializeAdif } from './adif'
import type { Qso } from './qso'

const SAMPLE = `Generated by Some Other Logger
<ADIF_VER:5>3.1.4
<PROGRAMID:6>Log4OM
<EOH>
<CALL:5>2E0XX <QSO_DATE:8>20260918 <TIME_ON:4>1432 <BAND:3>20m <MODE:3>FT8 <RST_SENT:3>-12 <RST_RCVD:3>-08 <EOR>
<CALL:4>W1AW <QSO_DATE:8>20260918 <TIME_ON:6>150312 <BAND:3>40m <FREQ:6>7.1740 <MODE:3>SSB <RST_SENT:2>59 <RST_RCVD:2>57 <GRIDSQUARE:6>FN31pr <COMMENT:12>Nice QSO, 73 <EOR>
`

function qso(overrides: Partial<Qso> = {}): Qso {
  return {
    id: '1',
    call: '2E0XXX',
    qsoDate: '20260918',
    timeOn: '1432',
    band: '20m',
    mode: 'FT8',
    ...overrides,
  }
}

describe('parseAdif', () => {
  it('reads the header and the records', () => {
    const file = parseAdif(SAMPLE)
    expect(file.header).toMatchObject({ ADIF_VER: '3.1.4', PROGRAMID: 'Log4OM' })
    expect(file.records).toHaveLength(2)
    expect(file.records[0]).toMatchObject({ CALL: '2E0XX', BAND: '20m', RST_SENT: '-12' })
  })

  it('accepts a file with no header', () => {
    const file = parseAdif('<CALL:4>W1AW <QSO_DATE:8>20260918 <EOR>')
    expect(file.header).toEqual({})
    expect(file.records).toHaveLength(1)
  })

  it('is case insensitive about field names and tags', () => {
    const file = parseAdif('<call:4>W1AW <qso_date:8>20260918 <eor>')
    expect(file.records[0]).toMatchObject({ CALL: 'W1AW', QSO_DATE: '20260918' })
  })

  it('accepts a type indicator', () => {
    const file = parseAdif('<CALL:4:S>W1AW <FREQ:6:N>14.074 <EOR>')
    expect(file.records[0]).toMatchObject({ CALL: 'W1AW', FREQ: '14.074' })
  })

  /**
   * The length is the contract: a value may hold anything, including the
   * characters that start a tag. A parser that scans for `<` instead of
   * counting corrupts the record that needed care most.
   */
  it('reads a value containing angle brackets', () => {
    const file = parseAdif('<CALL:4>W1AW <COMMENT:14>see <NOTES:1>x <EOR>')
    expect(file.records[0]?.COMMENT).toBe('see <NOTES:1>x')
    expect(file.records[0]?.NOTES).toBeUndefined()
  })

  it('keeps a record that is missing its EOR', () => {
    const file = parseAdif('<CALL:4>W1AW <QSO_DATE:8>20260918')
    expect(file.records).toHaveLength(1)
  })

  it('ignores an empty record', () => {
    expect(parseAdif('<EOR><EOR>').records).toEqual([])
  })

  it('handles an empty file', () => {
    expect(parseAdif('')).toEqual({ header: {}, records: [] })
  })

  it('handles records on one line and across lines', () => {
    const oneLine = parseAdif('<CALL:4>W1AW <EOR><CALL:5>2E0XX <EOR>')
    expect(oneLine.records).toHaveLength(2)
  })
})

describe('adifToQso', () => {
  it('maps the fields it models', () => {
    const [, second] = parseAdif(SAMPLE).records
    const contact = adifToQso(second ?? {}, 'id-1')

    expect(contact).toMatchObject({
      id: 'id-1',
      call: 'W1AW',
      qsoDate: '20260918',
      timeOn: '150312',
      band: '40m',
      freq: 7.174,
      mode: 'SSB',
      rstSent: '59',
      gridsquare: 'FN31pr',
      comment: 'Nice QSO, 73',
    })
  })

  // The fields that make a round trip lossless.
  it('keeps fields it does not model', () => {
    const contact = adifToQso(
      { CALL: 'W1AW', SIG: 'POTA', SIG_INFO: 'US-0001', MY_ANTENNA: 'dipole' },
      'id-1',
    )
    expect(contact.extra).toEqual({ SIG: 'POTA', SIG_INFO: 'US-0001', MY_ANTENNA: 'dipole' })
  })

  it('leaves extra out when there is nothing unknown', () => {
    expect(adifToQso({ CALL: 'W1AW' }, 'id-1').extra).toBeUndefined()
  })

  it('keeps an unreadable frequency rather than dropping it', () => {
    const contact = adifToQso({ CALL: 'W1AW', FREQ: 'not a number' }, 'id-1')
    expect(contact.freq).toBeUndefined()
    expect(contact.extra).toEqual({ FREQ: 'not a number' })
  })
})

describe('qsoToAdif', () => {
  it('writes the modelled fields', () => {
    expect(qsoToAdif(qso({ freq: 14.074, rstSent: '-12' }))).toEqual({
      CALL: '2E0XXX',
      QSO_DATE: '20260918',
      TIME_ON: '1432',
      BAND: '20m',
      FREQ: '14.074',
      MODE: 'FT8',
      RST_SENT: '-12',
    })
  })

  it('writes the unknown fields back', () => {
    expect(qsoToAdif(qso({ extra: { SIG: 'POTA' } }))).toMatchObject({ SIG: 'POTA' })
  })

  it('does not let a stale extra overwrite an edited field', () => {
    const contact = qso({ call: 'M0ABC', extra: { CALL: 'W1AW' } })
    expect(qsoToAdif(contact).CALL).toBe('M0ABC')
  })

  it('leaves out empty fields rather than writing blanks', () => {
    expect(qsoToAdif(qso({ comment: '' }))).not.toHaveProperty('COMMENT')
  })
})

describe('serializeAdif', () => {
  it('writes a header and one record per contact', () => {
    const text = serializeAdif([qso(), qso({ id: '2', call: 'W1AW' })])
    expect(text).toContain('<ADIF_VER:5>3.1.4')
    expect(text).toContain('<PROGRAMID:7>QSO Log')
    expect(text).toContain('<EOH>')
    expect(text.match(/<EOR>/g)).toHaveLength(2)
  })

  it('declares the length of every value in characters', () => {
    const text = serializeAdif([qso({ comment: 'Nice QSO, 73' })])
    expect(text).toContain('<COMMENT:12>Nice QSO, 73')
  })

  it('writes an empty log without records', () => {
    const text = serializeAdif([])
    expect(text).toContain('<EOH>')
    expect(text).not.toContain('<EOR>')
  })
})

describe('round trip', () => {
  it('survives export and import unchanged', () => {
    const contacts = [
      qso({ freq: 14.074, rstSent: '-12', rstRcvd: '-08', gridsquare: 'IO91wm' }),
      qso({ id: '2', call: 'W1AW', mode: 'SSB', comment: 'Nice QSO, 73', extra: { SIG: 'POTA' } }),
    ]

    const reimported = parseAdif(serializeAdif(contacts)).records.map((record, index) =>
      adifToQso(record, contacts[index]?.id ?? ''),
    )

    expect(reimported).toEqual(contacts)
  })

  it('survives a file from another logger unchanged through a second export', () => {
    const first = parseAdif(SAMPLE).records.map((record, index) => adifToQso(record, String(index)))
    const second = parseAdif(serializeAdif(first)).records.map((record, index) =>
      adifToQso(record, String(index)),
    )
    expect(second).toEqual(first)
  })

  it('keeps a comment containing angle brackets', () => {
    const contact = qso({ comment: 'worked <split> on 14.195' })
    const [record] = parseAdif(serializeAdif([contact])).records
    expect(adifToQso(record ?? {}, '1').comment).toBe('worked <split> on 14.195')
  })
})
