/**
 * Regenerates the DXCC prefix table from the Amateur Radio Country Files.
 *
 *   npm run sync:cty
 *
 * The data is maintained by Jim Reisert AD1C at country-files.com and is MIT
 * licensed; the notice travels in the generated file. It changes a few times a
 * year, when entities are added, removed, or renamed, so this is a deliberate
 * command rather than part of the build: a logbook that quietly changes what
 * it counted yesterday is worse than one that is a month out of date.
 */
import { unzipSync } from 'fflate'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const SOURCE = 'https://www.country-files.com/bigcty/download/bigcty.zip'
const root = resolve(fileURLToPath(new URL('.', import.meta.url)), '..')
const target = resolve(root, 'src/domain/dxcc.generated.ts')

interface Entity {
  dxcc: number
  prefix: string
  name: string
  continent: string
}

/** Strips cty.dat's per-prefix overrides: zones, coordinates, continents. */
function cleanPrefix(alias: string): string | undefined {
  const cleaned = alias
    .replace(/\([^)]*\)/g, '')
    .replace(/\[[^\]]*\]/g, '')
    .replace(/<[^>]*>/g, '')
    .replace(/\{[^}]*\}/g, '')
    .replace(/~[^~]*~/g, '')
    .trim()
  return /^[A-Z0-9/]+$/.test(cleaned) ? cleaned : undefined
}

const response = await fetch(SOURCE)
if (!response.ok) throw new Error(`Could not download ${SOURCE}: ${response.status}`)

const archive = unzipSync(new Uint8Array(await response.arrayBuffer()))
const csv = new TextDecoder().decode(archive['cty.csv'] ?? new Uint8Array())
if (!csv) throw new Error('cty.csv is missing from the archive')

const entities = new Map<number, Entity>()
const prefixes = new Map<string, number>()
const exact = new Map<number, string[]>()

for (const line of csv.split('\n')) {
  const row = line.trim().replace(/;$/, '')
  if (!row) continue

  const [primary, name, dxccText, continent, , , , , , aliases = ''] = row.split(',')
  const dxcc = Number(dxccText)
  if (!primary || !name || !Number.isFinite(dxcc) || dxcc === 0) continue

  // A leading * marks a WAE-only entity, such as Sicily. It carries its DXCC
  // parent's number, so keeping the non-WAE row for the name means those
  // prefixes count as Italy, which is what DXCC says they are.
  const isWae = primary.startsWith('*')
  if (!entities.has(dxcc) || !isWae) {
    entities.set(dxcc, {
      dxcc,
      prefix: primary.replace(/^\*/, ''),
      name: entities.get(dxcc) && isWae ? (entities.get(dxcc) as Entity).name : name,
      continent: continent ?? '',
    })
  }

  for (const alias of [primary, ...aliases.split(' ')]) {
    const token = alias.trim()
    if (!token) continue
    // An = entry is a callsign the file maps explicitly, because its prefix
    // would say the wrong thing. They are most of the file, and dropping them
    // put 13000 known callsigns in the wrong entity, so they are kept.
    if (token.startsWith('=')) {
      const call = cleanPrefix(token.slice(1))
      if (call) exact.set(dxcc, [...(exact.get(dxcc) ?? []), call])
      continue
    }
    const prefix = cleanPrefix(token.replace(/^\*/, ''))
    if (prefix) prefixes.set(prefix, dxcc)
  }
}

const sortedEntities = [...entities.values()].sort((a, b) => a.dxcc - b.dxcc)
const sortedPrefixes = [...prefixes.entries()].sort(([a], [b]) => a.localeCompare(b))
const sortedExact = [...exact.entries()].sort(([a], [b]) => a - b)
const exactCount = sortedExact.reduce((total, [, calls]) => total + calls.length, 0)

const file = `// Generated by scripts/sync-cty.ts. Do not edit.
//
// Source: Amateur Radio Country Files, ${SOURCE}
// Maintained by Jim Reisert, AD1C. Retrieved ${new Date().toISOString().slice(0, 10)}.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import type { DxccData } from './dxcc'

/** Entity list, keyed by ADIF DXCC number. */
const entities: DxccData['entities'] = {
${sortedEntities.map((e) => `  ${e.dxcc}: ['${e.name.replace(/'/g, "\\'")}', '${e.prefix}', '${e.continent}'],`).join('\n')}
}

/** Callsign prefix to DXCC number. Longest match wins. */
const prefixes: DxccData['prefixes'] = {
${sortedPrefixes.map(([prefix, dxcc]) => `  '${prefix}': ${dxcc},`).join('\n')}
}

/**
 * Callsigns whose prefix would say the wrong entity, as a space separated list
 * per DXCC number. One string per entity rather than a key per callsign: the
 * quotes and colons of ${exactCount} object keys cost more than the data.
 */
const exact: DxccData['exact'] = {
${sortedExact.map(([dxcc, calls]) => `  ${dxcc}: '${[...new Set(calls)].sort().join(' ')}',`).join('\n')}
}

const data: DxccData = { entities, prefixes, exact }

export default data
`

writeFileSync(target, file)
console.log(
  `Wrote ${sortedEntities.length} entities, ${sortedPrefixes.length} prefixes and ` +
    `${exactCount} exact callsigns to ${target}`,
)
